# Generated by Django 3.0.7 on 2020-06-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20200615_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sicklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
    ]
